/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct vectors {
	int n;
	struct {
		u_int x_len;
		int *x_val;
	} x;
	struct {
		u_int y_len;
		int *y_val;
	} y;
};
typedef struct vectors vectors;

struct average_result {
	double avg_x;
	double avg_y;
};
typedef struct average_result average_result;

struct scale_input {
	double r;
	int n;
	struct {
		u_int x_len;
		int *x_val;
	} x;
};
typedef struct scale_input scale_input;

struct scale_result {
	struct {
		u_int values_len;
		double *values_val;
	} values;
};
typedef struct scale_result scale_result;

#define CALC_PROG 0x23452222
#define CALC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define DOT_PRODUCT 1
extern  int * dot_product_1(vectors *, CLIENT *);
extern  int * dot_product_1_svc(vectors *, struct svc_req *);
#define AVERAGE_VECTORS 2
extern  average_result * average_vectors_1(vectors *, CLIENT *);
extern  average_result * average_vectors_1_svc(vectors *, struct svc_req *);
#define SCALE_VECTOR 3
extern  scale_result * scale_vector_1(scale_input *, CLIENT *);
extern  scale_result * scale_vector_1_svc(scale_input *, struct svc_req *);
extern int calc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define DOT_PRODUCT 1
extern  int * dot_product_1();
extern  int * dot_product_1_svc();
#define AVERAGE_VECTORS 2
extern  average_result * average_vectors_1();
extern  average_result * average_vectors_1_svc();
#define SCALE_VECTOR 3
extern  scale_result * scale_vector_1();
extern  scale_result * scale_vector_1_svc();
extern int calc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_vectors (XDR *, vectors*);
extern  bool_t xdr_average_result (XDR *, average_result*);
extern  bool_t xdr_scale_input (XDR *, scale_input*);
extern  bool_t xdr_scale_result (XDR *, scale_result*);

#else /* K&R C */
extern bool_t xdr_vectors ();
extern bool_t xdr_average_result ();
extern bool_t xdr_scale_input ();
extern bool_t xdr_scale_result ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_H_RPCGEN */
