/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calc.h"

bool_t
xdr_vectors (XDR *xdrs, vectors *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->n))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->x.x_val, (u_int *) &objp->x.x_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->y.y_val, (u_int *) &objp->y.y_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_average_result (XDR *xdrs, average_result *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->avg_x))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->avg_y))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_scale_input (XDR *xdrs, scale_input *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->r))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->n))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->x.x_val, (u_int *) &objp->x.x_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_scale_result (XDR *xdrs, scale_result *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->values.values_val, (u_int *) &objp->values.values_len, ~0,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}
