/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "calc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

int *
dot_product_1(vectors *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, DOT_PRODUCT,
		(xdrproc_t) xdr_vectors, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

average_result *
average_vectors_1(vectors *argp, CLIENT *clnt)
{
	static average_result clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, AVERAGE_VECTORS,
		(xdrproc_t) xdr_vectors, (caddr_t) argp,
		(xdrproc_t) xdr_average_result, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

scale_result *
scale_vector_1(scale_input *argp, CLIENT *clnt)
{
	static scale_result clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SCALE_VECTOR,
		(xdrproc_t) xdr_scale_input, (caddr_t) argp,
		(xdrproc_t) xdr_scale_result, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
